sudo: required
# what service needed to be used
services:
  - docker
before_install: 
  -docker build -t chamilg/docker-react -f Dockerfile.dev
  # Tell travis to run our testsuite
script: 
  - docker run -e CI=true chamilg/docker-react npm run test