sudo: required
# what service needed to be used
services:
  - docker
before_install: 
  -docker build -t chamilg/docker-react -f Dockerfile.dev
  # what should be done
script: 
  - docker run -e CI=true chamilg/docker-react npm run test